-- -----------------------------------------------------
-- Schema super-hero-films
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `super-hero-films`;

CREATE SCHEMA `super-hero-films`;
USE `super-hero-films` ;

-- -----------------------------------------------------
-- Table `super-hero-films`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `super-hero-films`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `super-hero-films`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `super-hero-films`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------

INSERT INTO product_category(CATEGORY_NAME) VALUES ('Android Phones');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Android Tablets');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Apple Phones');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Apple Tablets');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Laptops');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Books');

-- -----------------------------------------------------
-- Phones Tags
-- -----------------------------------------------------
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S20 Blue', 'Meet Galaxy S20, S20+ and S20 Ultra 5G. With revolutionary 8K Video Snap, 5G connectivity and Space Zoom up to 100x, the way you capture and share your life will never be the same. Shots you never even knew were there are suddenly just a tap away.', 'assets/images/products/androidPhones/Samsung_Galaxy_S20_Blue.jpg', 1, 100,499.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S20 Pink', 'Meet Galaxy S20, S20+ and S20 Ultra 5G. With revolutionary 8K Video Snap, 5G connectivity and Space Zoom up to 100x, the way you capture and share your life will never be the same. Shots you never even knew were there are suddenly just a tap away.', 'assets/images/products/androidPhones/Samsung_Galaxy_S20_Pink.jpg', 1, 100,499.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S20 Gray', 'Meet Galaxy S20, S20+ and S20 Ultra 5G. With revolutionary 8K Video Snap, 5G connectivity and Space Zoom up to 100x, the way you capture and share your life will never be the same. Shots you never even knew were there are suddenly just a tap away.', 'assets/images/products/androidPhones/Samsung_Galaxy_S20_Gray.jpg', 1, 100,499.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S20 Black', 'Meet Galaxy S20, S20+ and S20 Ultra 5G. With revolutionary 8K Video Snap, 5G connectivity and Space Zoom up to 100x, the way you capture and share your life will never be the same. Shots you never even knew were there are suddenly just a tap away.', 'assets/images/products/androidPhones/Samsung_Galaxy_S20_Black.jpg', 1, 100,499.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S10 Black', 'Samsung Galaxy S10 Factory Unlocked Android Cell Phone | US Version | 128GB of Storage | Fingerprint ID and Facial Recognition | Long-Lasting Battery | U.S. Warranty |  Prism White', 'assets/images/products/androidPhones/Samsung_Galaxy_S10_Black.jpg', 1, 100,599.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S10 White', 'Samsung Galaxy S10 Factory Unlocked Android Cell Phone | US Version | 128GB of Storage | Fingerprint ID and Facial Recognition | Long-Lasting Battery | U.S. Warranty |  Prism White', 'assets/images/products/androidPhones/Samsung_Galaxy_S10_White.jpg', 1, 100,599.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S10 Flamingo Pink', 'Samsung Galaxy S10 Factory Unlocked Android Cell Phone | US Version | 128GB of Storage | Fingerprint ID and Facial Recognition | Long-Lasting Battery | U.S. Warranty |  Prism White', 'assets/images/products/androidPhones/Samsung_Galaxy_S10_Flamingo_Pink.jpg', 1, 100,599.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S10 Prism Blue', 'Samsung Galaxy S10 Factory Unlocked Android Cell Phone | US Version | 128GB of Storage | Fingerprint ID and Facial Recognition | Long-Lasting Battery | U.S. Warranty |  Prism White', 'assets/images/products/androidPhones/Samsung_Galaxy_S10_Prism_Blue.jpg', 1, 100,599.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S9 Black', 'Samsung Galaxy S9 Factory Unlocked Smartphone 64GB - Lilac Purple - US Version [SM-G960UZPAXAA]', 'assets/images/products/androidPhones/Samsung_Galaxy_S9_Black.jpg', 1, 100,238.00, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S9 Colar Blue', 'Samsung Galaxy S9 Factory Unlocked Smartphone 64GB - Lilac Purple - US Version [SM-G960UZPAXAA]', 'assets/images/products/androidPhones/Samsung_Galaxy_S9_Colar_Blue.jpg', 1, 100,238.00, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy S9 Lilac Purple', 'Samsung Galaxy S9 Factory Unlocked Smartphone 64GB - Lilac Purple - US Version [SM-G960UZPAXAA]', 'assets/images/products/androidPhones/Samsung_Galaxy_S9_Lilac_Purple.jpg', 1, 100,238.00, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Huawei P30 Lite (128GB, 4GB RAM) 6.15 Midnight Black', 'Huawei P30 Lite (128GB, 4GB RAM) 6.15" Display, AI Triple Camera, 32MP Selfie, Dual SIM Global 4G LTE GSM Factory Unlocked MAR-LX3A - International Version (Midnight Black)', 'assets/images/products/androidPhones/Huawei_P30_Lite_(128GB,_4GB_RAM)_6.15_Midnight_Black.jpg', 1, 100,204.00, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Huawei P30 Lite (128GB, 4GB RAM) 6.15 Pearl White', 'Huawei P30 Lite (128GB, 4GB RAM) 6.15" Display, AI Triple Camera, 32MP Selfie, Dual SIM Global 4G LTE GSM Factory Unlocked MAR-LX3A - International Version (Midnight Black)', 'assets/images/products/androidPhones/Huawei_P30_Lite_(128GB,_4GB_RAM)_6.15_Pearl_White.jpg', 1, 100,204.00, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Huawei Y9 Prime 2019 (128GB, 4GB RAM) 6.59', 'Huawei Y9 Prime 2019 (128GB, 4GB RAM) 6.59" Display, 3 AI Cameras, 4000mAh Battery, Dual SIM GSM Factory Unlocked - STK-LX3, US & Global 4G LTE International Model (Sapphire Blue, 128 GB)', 'assets/images/products/androidPhones/Huawei_Y9_Prime_2019_(128GB,_4GB_RAM)_6.59.jpg', 1, 100,200.00, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Honor 9X (128GB, 6GB) 6.59', 'Honor 9X (128GB, 6GB) 6.59", 3 AI Cameras, 4000mAh Battery, Dual SIM GSM Unlocked US + Global 4G LTE International Model STK-LX3 (Blue, 128GB + 64GB SD + Case Bundle)', 'assets/images/products/androidPhones/Honor_9X_(128GB,_6GB)_6.59.jpg', 1, 100,224.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Huawei Nova 5T (128GB, 8GB) 6.26', 'Huawei Nova 5T (128GB, 8GB) 6.26" LCD, Kirin 980, 48MP Quad Camera, 22.5W Fast Charge, Dual SIM GSM Unlocked Global 4G LTE International Model YAL-L21 (Crush Blue)', 'assets/images/products/androidPhones/Huawei_Nova_5T_(128GB,_8GB)_6.26.jpg', 1, 100,377.49, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Huawei Honor 8X (64GB + 4GB RAM) 6.5', 'Huawei Honor 8X (64GB + 4GB RAM) 6.5" HD 4G LTE GSM Factory Unlocked Smartphone - International Version No Warranty JSN-L23 (Black)', 'assets/images/products/androidPhones/Huawei_Honor_8X_(64GB_+_4GB_RAM)_6.5.jpg', 1, 100,189.99, 1, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy Tab S6', 'Samsung Galaxy Tab S6 10.5",  128GB Wifi Tablet Cloud Blue - SM-T860NZBAXAR', 'assets/images/products/androidTablets/Samsung_Galaxy_Tab_S6.jpg', 1, 100,529.99, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Samsung Galaxy Tab S6 With Keyboard', 'Samsung Galaxy Tab S6 10.5",  128GB Wifi Tablet Cloud Blue - SM-T860NZBAXAR', 'assets/images/products/androidTablets/Samsung_Galaxy_Tab_S6_With_Keyboard.jpg', 1, 100,687.98, 2, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPhone 11, 128GB, Black', 'Just the right amount of everything. A new dual‑camera system captures more of what you see and love. The fastest chip ever in a smartphone and all‑day battery life let you do more and charge less.', 'assets/images/products/applePhones/Apple_iPhone_11,_128GB,_Black.jpg', 1, 100,799.00, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPhone 11, 128GB, Red', 'Just the right amount of everything. A new dual‑camera system captures more of what you see and love. The fastest chip ever in a smartphone and all‑day battery life let you do more and charge less.', 'assets/images/products/applePhones/Apple_iPhone_11,_128GB,_Red.jpg', 1, 100,799.00, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPhone 11, 128GB, Green', 'Just the right amount of everything. A new dual‑camera system captures more of what you see and love. The fastest chip ever in a smartphone and all‑day battery life let you do more and charge less.', 'assets/images/products/applePhones/Apple_iPhone_11,_128GB,_Green.jpg', 1, 100,799.00, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPhone 11, 128GB, Purple', 'Just the right amount of everything. A new dual‑camera system captures more of what you see and love. The fastest chip ever in a smartphone and all‑day battery life let you do more and charge less.', 'assets/images/products/applePhones/Apple_iPhone_11,_128GB,_Purple.jpg', 1, 100,799.00, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPhone 11, 128GB, White', 'Just the right amount of everything. A new dual‑camera system captures more of what you see and love. The fastest chip ever in a smartphone and all‑day battery life let you do more and charge less.', 'assets/images/products/applePhones/Apple_iPhone_11,_128GB,_White.jpg', 1, 100,799.00, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPhone 11, 128GB, Yellow', 'Just the right amount of everything. A new dual‑camera system captures more of what you see and love. The fastest chip ever in a smartphone and all‑day battery life let you do more and charge less.', 'assets/images/products/applePhones/Apple_iPhone_11,_128GB,_Yellow.jpg', 1, 100,799.00, 3, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPad mini (Wi-Fi, 64GB) - Gold', 'With its thin, light design and 10-hour battery life, you cant take it anywhere and use it all day.', 'assets/images/products/appleTablets/Apple_iPad_mini_(Wi-Fi,_64GB)_-_Gold.jpg', 1, 100,349.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPad mini (Wi-Fi, 64GB) - Silver', 'With its thin, light design and 10-hour battery life, you cant take it anywhere and use it all day.', 'assets/images/products/appleTablets/Apple_iPad_mini_(Wi-Fi,_64GB)_-_Silver.jpg', 1, 100,349.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Apple iPad mini (Wi-Fi, 64GB) - Space Gray', 'With its thin, light design and 10-hour battery life, you cant take it anywhere and use it all day.', 'assets/images/products/appleTablets/Apple_iPad_mini_(Wi-Fi,_64GB)_-_Space_Gray.jpg', 1, 100,349.99, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'New Apple iPad Pro (12.9-inch, Wi-Fi, 128GB) - Silver (4th Generation)', '12.9-inch edge-to-edge Liquid Retina display with ProMotion, True Tone, and P3 wide c', 'assets/images/products/appleTablets/New_Apple_iPad_Pro_(12.9-inch,_Wi-Fi,_128GB)_-_Silver_(4th_Generation).jpg', 1, 100,1499.00, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'New Apple iPad Pro (12.9-inch, Wi-Fi, 128GB) - Space Gray (4th Generation)', '12.9-inch edge-to-edge Liquid Retina display with ProMotion, True Tone, and P3 wide c', 'assets/images/products/appleTablets/New_Apple_iPad_Pro_(12.9-inch,_Wi-Fi,_128GB)_-_Space_Gray_(4th_Generation).jpg', 1, 100,1499.00, 4, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'ASUS ZenBook 13 Ultra Slim Laptop, 13.3', 'ASUS ZenBook 13 Ultra Slim Laptop, 13.3” FHD WideView, 8th-Gen Intel Core i7-8565U CPU, 16GB RAM, 512GB PCIe SSD, Backlit KB, NumberPad, Military Grade, TPM, Windows 10 Pro, UX333FA-AB77, Royal Blue', 'assets/images/products/laptops/ASUS_ZenBook_13_Ultra_Slim_Laptop,_13.3.jpg', 1, 100,975.32, 5, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'ASUS VivoBook 15 Thin and Light Laptop, 15.6', 'ASUS VivoBook 15 Thin and Light Laptop, 15.6” FHD, Intel i5-1035G1 CPU, 8GB RAM, 512GB SSD, Backlit KB, Fingerprint, Windows 10, Slate Gray, F512JA-AS54', 'assets/images/products/laptops/ASUS_VivoBook_15_Thin_and_Light_Laptop,_15.6.jpg', 1, 100,599.99, 5, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'ASUS TUF Gaming A15 Gaming Laptop, 15.6', 'ASUS TUF Gaming A15 Gaming Laptop, 15.6” 144Hz FHD IPS-Type, AMD Ryzen 5 4600H, GeForce GTX 1650, 8GB DDR4, 512GB PCIe SSD, Gigabit Wi-Fi 5, Windows 10 Home, FA506IH-AS53', 'assets/images/products/laptops/ASUS_TUF_Gaming_A15_Gaming_Laptop,_15.6.jpg', 1, 100,749.99, 5, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Acer Swift 3 Thin & Light Laptop, 14', 'Acer Swift 3 Thin & Light Laptop, 14" Full HD IPS, AMD Ryzen 7 4700U Octa-Core with Radeon Graphics, 8GB LPDDR4, 512GB NVMe SSD, WiFi 6, Backlit KB, Fingerprint Reader, Alexa Built-in, SF314-42-R9YN', 'assets/images/products/laptops/Acer_Swift_3_Thin_&_Light_Laptop,_14.jpg', 1, 100,679.99, 5, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Acer Nitro 5 Gaming Laptop, 9th Gen Intel Core i7', 'Acer Nitro 5 Gaming Laptop, 9th Gen Intel Core i7-9750H, NVIDIA GeForce RTX 2060, 15.6" Full HD IPS 144Hz Display, 16GB DDR4, 256GB NVMe SSD, WiFi 6, Waves MaxxAudio, Backlit Keyboard, AN515-54-728C', 'assets/images/products/laptops/Acer_Nitro_5_Gaming_Laptop,_9th_Gen_Intel_Core_i7.jpg', 1, 100,1018.07, 5, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Acer Predator Helios 300 Gaming Laptop, Intel i7', 'Acer Predator Helios 300 Gaming Laptop, Intel i7-10750H, NVIDIA GeForce RTX 2060 6GB, 15.6" Full HD 144Hz 3ms IPS Display, 16GB Dual-Channel DDR4, 512GB NVMe SSD, WiFi 6, RGB Keyboard, PH315-53-72XD', 'assets/images/products/laptops/Acer_Predator_Helios_300_Gaming_Laptop,_Intel_i7.jpg', 1, 100,1199.99, 5, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Hands-On Microservices with Spring Boot and Spring Cloud - Build and deploy Java microservices using Spring Cloud, Istio, and Kubernetes', 'Apply microservices patterns to build resilient and scalable distributed systems', 'assets/images/products/books/Hands-On_Microservices_with_Spring_Boot_and_Spring_Cloud_-_Build_and_deploy_Java_microservices_using_Spring_Cloud,_Istio,_and_Kubernetes.jpg', 1, 100,39.99, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Learning Spring Boot 2.0 - Second Edition - Simplify the development of lightning fast applications based on microservices and reactive programming', 'Get up to date with the defining characteristics of Spring Boot 2.0 in Spring Framework 5, Learn to perform Reactive programming with SpringBoot, Learn about developer tools, AMQP messaging, WebSockets, security, MongoDB data access, REST, and more', 'assets/images/products/books/Learning_Spring_Boot_2.0_-_Second_Edition_-_Simplify_the_development_of_lightning_fast_applications_based_on_microservices_and_reactive_programming.jpg', 1, 100,24.63, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Spring Boot in Action', 'A developer-focused guide to writing applications using Spring Boot. You will learn how to bypass the tedious configuration steps so that you can concentrate on your application.', 'assets/images/products/books/Spring_Boot_in_Action.jpg', 1, 100,28.94, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Pro Angular 9 - Build Powerful and Dynamic Web Apps 4th ed. Edition', 'Welcome to this one-stop-shop for learning Angular. Pro Angular is the most concise and comprehensive guide available, giving you the knowledge you need to take full advantage of this popular framework.', 'assets/images/products/books/Pro_Angular_9_-_Build_Powerful_and_Dynamic_Web_Apps_4th_ed._Edition.jpg', 1, 100,27.80, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Angular for Enterprise-Ready Web Applications', 'Angular for Enterprise-Ready Web Applications: Build and deliver production-grade and cloud-scale evergreen web apps with Angular 9 and beyond, 2nd Edition', 'assets/images/products/books/Angular_for_Enterprise-Ready_Web_Applications.jpg', 1, 100,29.25, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Angular Development with TypeScript 2nd Edition', 'Angular Development with TypeScript, Second Edition is an intermediate-level tutorial that introduces Angular and TypeScript to developers comfortable with building web applications using other frameworks and tools.', 'assets/images/products/books/Angular_Development_with_TypeScript_2nd_Edition.jpg', 1, 100,29.26, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Beginning Angular with Typescript (updated to Angular 9)', 'Angular is one of the leading frameworks to develop apps across all platforms. Reuse your code and build fast and high performing apps for any platform be it web, mobile web, native mobile and native desktop.', 'assets/images/products/books/Beginning_Angular_with_Typescript_(updated_to_Angular_9).jpg', 1, 100,29.27, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Web Development with Angular and Bootstrap', 'Web Development with Angular and Bootstrap: Embrace responsive web design and build adaptive Angular web applications, 3rd Edition', 'assets/images/products/books/Web_Development_with_Angular_and_Bootstrap.jpg', 1, 100,34.99, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'ng-book - The Complete Guide to Angular', 'What if you could master the entire framework - with solid foundations - in less time without beating your head against a wall? Imagine how quickly you could work if you knew the best practices and the best tools?', 'assets/images/products/books/ng-book_-_The_Complete_Guide_to_Angular.jpg', 1, 100,59.00, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Angular - Up and Running - Learning Angular, Step by Step', 'If you’re familiar with JavaScript, this hands-on guide will quickly get you up to speed on the Angular framework for building high-performance web-based desktop, mobile, and single-page applications.', 'assets/images/products/books/Angular_-_Up_and_Running_-_Learning_Angular,_Step_by_Step.jpg', 1, 100,24.99, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Angular for Material Design', 'Angular for Material Design: Leverage Angular Material and TypeScript to Build a Rich User Interface for Web Apps.', 'assets/images/products/books/Angular_for_Material_Design.jpg', 1, 100,30.39, 6, NOW());
INSERT INTO PRODUCT (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LUGGAGETAG-1024', 'Testing Angular Applications', 'Testing Angular Applications is an example-rich, hands-on guide that gives you the real-world techniques you need to thoroughly test all parts of your Angular applications.', 'assets/images/products/books/Testing_Angular_Applications.jpg', 1, 100,38.07, 6, NOW());
